//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onePunch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public byte[] pwUsuario { get; set; }
        public Nullable<int> idPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
